[package]
name = "ug_05_editor"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
description = "ug_05_editor —— ui-gpui 的多行编辑器演示"

[dependencies]
gpui = { workspace = true }
ui-gpui = { path = "../../packages/ui-gpui" }

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
gpui_platform = { workspace = true, features = ["font-kit", "wayland", "x11"] }

[target.'cfg(not(any(target_os = "linux", target_os = "freebsd", target_family = "wasm")))'.dependencies]
gpui_platform = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
gpui_platform = { workspace = true }
wasm-bindgen = "0.2.120"
